nginx:
  image: nginx:latest
  volumes:
    - "./nginx/config:/etc/nginx/"
  ports:
    - "80:80"

console:
  build: "./console/"
  volumes:
    - "./console/public:/code/console/public"
  ports:
    - "8001:3000"
  command: gulp serve

stop_finder:
  build: "./stop_finder/"
  volumes:
   - "./stop_finder:/code/stop_finder"
  environment:
    CONFIG_PATH: "/code/stop_finder/config/stop_finder.cfg"
  links:
    - elasticsearch
  ports:
    - "8002:5000"
  command: python main.py

core:
  build: "./core/"
  volumes:
   - "./core:/code/core"
  environment:
    CONFIG_PATH: "/code/core/config/core.cfg"
  links:
    - postgres
  ports:
    - "8003:5000"
  command: python main.py

sync:
  build: "./sync/"
  volumes:
   - "./sync:/code/sync"
  environment:
    CONFIG_PATH: "/code/sync/config/sync.cfg"
  links:
    - postgres
    - elasticsearch
  ports:
    - "8004:5000"
  command: python main.py
  # command: celery worker -A app:celery -l DEBUG

postgres:
  image: postgres:9.4.5
  volumes:
    - /home/storage/postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: "mysecretpassword"
  ports:
    - "5432:5432"

elasticsearch:
  image: elasticsearch:2.1.0
  volumes:
    - /home/storage/elasticsearch:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"